services:
  comfyui:
    restart: unless-stopped
    container_name: comfyui
    ports:
      - 7860:7860
    volumes:
      - ./data_folder/comfyui/data:/data
      - ./data_folder/comfyui/output:/output
    tty: true
    stop_signal: SIGKILL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids:
                - "0"
              capabilities:
                - compute
                - utility
    image: tbd
    environment:
      - CLI_ARGS=--listen
    network_mode: gf_network
  
  ollama:
    restart: unless-stopped
    volumes:
      - ./data_folder/ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    image: ollama/ollama:latest
    hostname: ollama
    network_mode: gf_network
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
  
  redis_n8n_ollama:
    container_name: redis_n8n_ollama
    image: redis:latest
    environment:
      - TZ=Europe/Berlin
      - TCP_PORT_6379=6379
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_EXTRA_FLAGS=--auto-aof-rewrite-percentage 100
        --auto-aof-rewrite-min-size 1mb
      - PUID=99
      - PGID=100
    volumes:
      - ./data_folder/redis_n8n_ollama/data:/data:rw
    network_mode: docker
    restart: unless-stopped
  
  n8n_main:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n_main
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.entryPoints=https
      - traefik.http.routers.n8n.rule=Host(`n8n.your_custom_domain.com`)
      - traefik.http.services.n8n.loadbalancer.server.port=5678
    environment:
      - PUID=99
      - PGID=100
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=change_my_value
      - NODE_OPTIONS="--max-old-space-size=4096"
      - N8N_HOST=n8n.your_custom_domain.com
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.your_custom_domain.com
    ports:
      - 5678:5678
    command: start
    volumes:
      - ./data_folder/n8n:/home/node/.n8n
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres_n8n
      - redis_n8n_ollama
    network_mode: gf_network
    restart: unless-stopped
  
  kokoro-fastapi-gpu:
    container_name: kokoro-fastapi-gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 8880:8880
    image: ghcr.io/remsky/kokoro-fastapi-gpu:v0.2.2
    network_mode: docker
    restart: unless-stopped
    
networks:
  gf_network:
    external: true
